---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1852,"creation_ts":"2013-08-29 05:42:00 -0700","short_desc":"8.3.16.6: Missing ReturnIfAbrupt after step 2","delta_ts":"2013-10-29 09:46:49 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 17: August 23, 2013 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"andrebargull","name":"André Bargull"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":5260,"comment_count":0,"who":{"uid":"andrebargull","name":"André Bargull"},"bug_when":"2013-08-29 05:42:48 -0700","thetext":"8.3.16.6 calls DefinePropertyOrThrow() in step 2, but it is not followed by ReturnIfAbrupt(), so the exception is effectively ignored."},{"commentid":6010,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-10-28 12:14:56 -0700","thetext":"fixed in rev20 editor's draft"},{"commentid":6163,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-10-29 09:46:49 -0700","thetext":"fixed in rev20 draft, Oct. 28, 2013"}]}}
---
