---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1875,"creation_ts":"2013-08-30 12:39:00 -0700","short_desc":"15.4.3.4.1: Return false instead of throwing TypeError for non-objects","delta_ts":"2013-09-27 14:47:20 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 17: August 23, 2013 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"andrebargull","name":"André Bargull"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":5287,"comment_count":0,"who":{"uid":"andrebargull","name":"André Bargull"},"bug_when":"2013-08-30 12:39:07 -0700","thetext":"15.4.3.4.1, step 2 should simply return `false` instead of throwing a TypeError. Otherwise this throws an error `[].concat(1)`. \n\nAlso the ReturnIfAbrupt() in step 1 seems unnecessary."},{"commentid":5391,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-09-12 17:09:42 -0700","thetext":"fixed in rev19 editor's draft"},{"commentid":5533,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-09-27 14:47:20 -0700","thetext":"fixed in rev19"}]}}
---
