---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":240,"creation_ts":"2012-01-10 04:54:00 -0800","short_desc":"UTF-8 BOM makes parseTestRecord fail for certain tests","delta_ts":"2012-03-28 16:31:53 -0700","product":"Test262","component":"Test Harness","version":"unspecified","rep_platform":"Macintosh","op_sys":"Mac OS","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"joost-wim","name":"Joost-Wim Boekesteijn"},"assigned_to":{"uid":"dfugate","name":"Dave Fugate"},"long_desc":[{"commentid":551,"comment_count":0,"who":{"uid":"joost-wim","name":"Joost-Wim Boekesteijn"},"bug_when":"2012-01-10 04:54:01 -0800","thetext":"When running the tests for ch07 or ch15, the command line test runner fails with this message:\n\nTraceback (most recent call last):\n  File \"tools/packaging/test262.py\", line 453, in <module>\n    Main()\n  File \"tools/packaging/test262.py\", line 448, in Main\n    options.full_summary)\n  File \"tools/packaging/test262.py\", line 412, in Run\n    cases = self.EnumerateTests(tests)\n  File \"tools/packaging/test262.py\", line 363, in EnumerateTests\n    strict_case = TestCase(self, name, full_path, True)\n  File \"tools/packaging/test262.py\", line 185, in __init__\n    del testRecord[\"commentary\"]\nKeyError: 'commentary'\n\nThe problem seems to be that some files start with a UTF-8 Byte Order Mark (which ends up in the source string) causing the parseTestRecord function to fail.\n\nMy guess is that there are two approaches to fixing this:\n\n1. Removing the BOM from the offending files. Using the next command, I produced a list of these files:\n\nfind ./test/suite -name '*.js' | xargs file | grep BOM\n\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-2-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-3-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-4-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-5-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-6-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-7-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-8-s.js\n./test/suite/ch07/7.6/7.6.1/7.6.1.2/7.6.1.2-9-s.js\n./test/suite/ch15/15.11/15.11.4/15.11.4.2/15.11.4.2-1.js\n./test/suite/ch15/15.11/15.11.4/15.11.4.3/15.11.4.3-1.js\n\nI'm not sure if the BOM is there for any reason. Probably not.\n\n2. Changing the way the files are read.\n\nAs a quick hack, I changed TestCase.__init__ in tools/packaging/test262.py by replacing the call to 'open' with 'codecs.open':\n\n-f = open(self.full_path)\n+f = codecs.open(self.full_path, \"r\", \"utf-8-sig\")\n\nWith this change, Python skips the BOM when reading the file. This also needs an extra line 'import codecs' at the top of the file.\n\nTested with Python 2.7.1 on OS X 10.7.2 against revision 282, changeset 99ff7d59530c."},{"commentid":552,"comment_count":1,"who":{"uid":"dfugate","name":"Dave Fugate"},"bug_when":"2012-01-10 09:42:18 -0800","thetext":"Changing open(self.full_path) to open(self.full_path, 'rb') might be a smaller fix."},{"commentid":553,"comment_count":2,"who":{"uid":"joost-wim","name":"Joost-Wim Boekesteijn"},"bug_when":"2012-01-10 09:56:25 -0800","thetext":"(In reply to comment #1)\n> Changing open(self.full_path) to open(self.full_path, 'rb') might be a smaller\n> fix.\n\nIn fact, specifying 'rb' does not change the way the BOM is handled. To illustrate this, I created a text file containing the word 'test' and saved it as UTF-8 with a BOM.\n\nReading this file in different ways then yields these results:\n\nPython 2.7.1 (r271:86832, Jun 25 2011, 05:09:01) \n[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> open(\"withbom.txt\").read()\n'\\xef\\xbb\\xbftest'\n>>> open(\"withbom.txt\", \"rb\").read()\n'\\xef\\xbb\\xbftest'\n>>> import codecs\n>>> codecs.open(\"withbom.txt\", \"r\", \"utf-8-sig\").read()\nu'test'"},{"commentid":755,"comment_count":3,"who":{"uid":"joost-wim","name":"Joost-Wim Boekesteijn"},"bug_when":"2012-03-13 06:14:09 -0700","thetext":"Update: in revision 324, there is a single file left that starts with a UTF-8 Byte Order Mark. From the root directory, running the command from the first line returns the filename on the second line:\n\n> find ./test/suite -name '*.js' | xargs file | grep BOM\n> ./test/suite/ch07/7.8/7.8.5/S7.8.5_A3.1_T7.js\n\nThis is also the only file that results in a KeyError on this line from test262.py:\n\n> del testRecord[\"commentary\"]\n\nIf the BOM is removed from this single file, https://bugs.ecmascript.org/show_bug.cgi?id=271 will also be solved since the BOM is the only thing that causes the KeyError on the commentary key."},{"commentid":758,"comment_count":4,"who":{"uid":"dfugate","name":"Dave Fugate"},"bug_when":"2012-03-14 14:25:01 -0700","thetext":"Should be fixed now."},{"commentid":760,"comment_count":5,"who":{"uid":"joost-wim","name":"Joost-Wim Boekesteijn"},"bug_when":"2012-03-14 14:57:13 -0700","thetext":"Thanks! Issue is indeed resolved, the KeyError has disappeared."}]}}
---
