---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":707,"creation_ts":"2012-10-03 12:47:00 -0700","short_desc":"15.5.4.21: \"rhow\"","delta_ts":"2013-10-22 19:25:50 -0700","product":"Draft for 6th Edition","component":"editorial issue","version":"Rev 10: September 27, 2012 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"jmdyck","name":"Michael Dyck"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":1828,"comment_count":0,"who":{"uid":"jmdyck","name":"Michael Dyck"},"bug_when":"2012-10-03 12:47:22 -0700","thetext":"In 15.5.4.21 \"String.prototype.repeat (count)\",\nstep 7 says:\n     If n is +[infinity], then rhow a RangeError Exception.\n\nChange \"rhow\" to \"throw\".\n\n(And maybe de-capitalize \"Exception\".)"},{"commentid":2048,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2012-10-25 15:22:57 -0700","thetext":"corrected in editor's rev 11 draft"}]}}
---
