<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] Unable to throw custom exceptions -	possiblebug?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Unable%20to%20throw%20custom%20exceptions%20-%0A%09possiblebug%3F&In-Reply-To=%3C04E8F83D0845412AA15FD28995988924%40Atlantis%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="023896.html">
   <LINK REL="Next"  HREF="023900.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] Unable to throw custom exceptions -	possiblebug?</H1>
    <B>Lorenzo Dalla Vecchia</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Unable%20to%20throw%20custom%20exceptions%20-%0A%09possiblebug%3F&In-Reply-To=%3C04E8F83D0845412AA15FD28995988924%40Atlantis%3E"
       TITLE="[antlr-interest] Unable to throw custom exceptions -	possiblebug?">lor.dv at tiscali.it
       </A><BR>
    <I>Sun Sep 30 03:03:26 PDT 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="023896.html">[antlr-interest] Unable to throw custom exceptions - possible	bug?
</A></li>
        <LI>Next message: <A HREF="023900.html">[antlr-interest] Unable to throw custom exceptions - possiblebug?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23899">[ date ]</a>
              <a href="thread.html#23899">[ thread ]</a>
              <a href="subject.html#23899">[ subject ]</a>
              <a href="author.html#23899">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;&gt;<i> [...] I added
</I>&gt;&gt;<i> &quot;throws MyException&quot; to the rule declaration in order to declare the
</I>&gt;&gt;<i> exception throwing in the parser code.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The modified grammar compiles correctly with antlr Tool, but nothing is
</I>&gt;&gt;<i> added to the method signature in the generated parser! Is this a bug?
</I>&gt;&gt;<i> Maybe the reason is that I am using a return value for the rule?
</I>&gt;<i>
</I>&gt;<i> Looks to me like you stumbled upon an open TODO issue. The ANTLR grammar
</I>&gt;<i> does infact recognizer 'throws' declarations, but I can't see anything in
</I>&gt;<i> the codegen templates that actually makes use of this. But I'm the Python
</I>&gt;<i> guy here, so I don't care about such formalities anyway ;)
</I>
I'm using Java as output language.
Anyway, I see the problem.

I wonder what would be my best option to signal the error to the code that 
called the parser without using custom exceptions. Any ideas?

Thanks.

--
Lorenzo 

</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="023896.html">[antlr-interest] Unable to throw custom exceptions - possible	bug?
</A></li>
	<LI>Next message: <A HREF="023900.html">[antlr-interest] Unable to throw custom exceptions - possiblebug?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23899">[ date ]</a>
              <a href="thread.html#23899">[ thread ]</a>
              <a href="subject.html#23899">[ subject ]</a>
              <a href="author.html#23899">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
