<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.ecmascript.org/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.4+"
          urlbase="https://bugs.ecmascript.org/"
          
          maintainer="dherman@mozilla.com"
>

    <bug>
          <bug_id>69</bug_id>
          
          <creation_ts>2011-03-14 12:54:00 -0700</creation_ts>
          <short_desc>Test 15.4.4.4-5-c-i-1 issues</short_desc>
          <delta_ts>2011-05-18 15:38:13 -0700</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>Test262</product>
          <component>ECMA-262 Tests</component>
          <version>unspecified</version>
          <rep_platform>PC</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>Normal</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="David Bruant">bruant.d</reporter>
          <assigned_to name="Dave Fugate">dfugate</assigned_to>
          
          

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>152</commentid>
    <comment_count>0</comment_count>
    <who name="David Bruant">bruant.d</who>
    <bug_when>2011-03-14 12:54:52 -0700</bug_when>
    <thetext>Test case is:
------------------
function testcase() {
    try {
        Object.defineProperty(Array.prototype, &quot;0&quot;, {value: 100, writable: false, configurable: true});
        var newArr = Array.prototype.concat.call(101);
        return newArr.hasOwnProperty(&quot;0&quot;) &amp;&amp; newArr[0] === 101;
        var verifyValue = false;

        (...)

        return verifyValue &amp;&amp;
            !verifyConfigurable &amp;&amp; verifyEnumerable &amp;&amp; verifyWritable;
    } finally {
        delete Array.prototype[0];
    }
}
------------------

There is a return in the middle of the try block.
Moreover, there is something weird with the &quot;Array.prototype.concat.call(101);&quot;
The first argument of call is usually an object used as the |this| binding. I think that here, the intention was to write Array.prototype.concat(101) in order to perform the concat on the Array.prototype object itself (which is itself an array)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>209</commentid>
    <comment_count>1</comment_count>
    <who name="Dave Fugate">dfugate</who>
    <bug_when>2011-05-12 14:06:33 -0700</bug_when>
    <thetext>I&apos;ve simply disabled this one until sense can be made of it with the original author.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>215</commentid>
    <comment_count>2</comment_count>
    <who name="Dave Fugate">dfugate</who>
    <bug_when>2011-05-18 15:38:13 -0700</bug_when>
    <thetext>The fix provided to me has been checked into Hg.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>