<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] FailedPredicateException leads to infinite loop - bug in the Lexer?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20FailedPredicateException%20leads%20to%20infinite%0A%20loop%20-%20bug%20in%20the%20Lexer%3F&In-Reply-To=%3C4BB23BC3.9020101%40oracle.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="038092.html">
   <LINK REL="Next"  HREF="038095.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] FailedPredicateException leads to infinite loop - bug in the Lexer?</H1>
    <B>Ron Hunter-Duvar</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20FailedPredicateException%20leads%20to%20infinite%0A%20loop%20-%20bug%20in%20the%20Lexer%3F&In-Reply-To=%3C4BB23BC3.9020101%40oracle.com%3E"
       TITLE="[antlr-interest] FailedPredicateException leads to infinite loop - bug in the Lexer?">ron.hunter-duvar at oracle.com
       </A><BR>
    <I>Tue Mar 30 10:58:27 PDT 2010</I>
    <P><UL>
        <LI>Previous message: <A HREF="038092.html">[antlr-interest] FailedPredicateException leads to infinite	loop - bug in the Lexer?
</A></li>
        <LI>Next message: <A HREF="038095.html">[antlr-interest] FailedPredicateException leads to infinite	loop - bug in the Lexer?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#38093">[ date ]</a>
              <a href="thread.html#38093">[ thread ]</a>
              <a href="subject.html#38093">[ subject ]</a>
              <a href="author.html#38093">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>The message title was: &quot;Antlr Bug: Failed semantic predicate in lexer    
triggers endless loop&quot;

Basically, the bug is in the nextToken() method in Antlr's Lexer class. 
If a NoViableAlt exception is thrown, the method calls the recover 
method, which consumes one character before trying again. But if any 
other RecognitionException (including a FailedPredicateException) is 
thrown, it doesn't call recover, it just reports the exception and loops 
back to try again at the same point, which of course results in the same 
exception, because nothing has changed. I just added a recover call to 
the second catch block, and it solved the problem.

As I mentioned, I did this as an overriding method in a custom 
superclass. You could also fix it directly in the Antlr source, but then 
you'd have to rebuild Antlr.

I'm not sure this ever got reported as an official bug. Jim Idle 
disputed whether it was an Antlr bug. I sent proof, but not sure it was 
even looked at. Unfortunately, because of the (quite reasonable) legal 
agreement required to submit bug reports, and the fact that I'm doing 
this as an employee, I can't submit bug reports or fixes until I get 
approval to do so (seems ridiculous at first glance, but in today's 
legal climate I can't take chances).

Ron


Cliff Hudson wrote:
&gt;<i> I've been all over the archives, but perhaps my search terms were 
</I>&gt;<i> inadequate.  I'll look again with that date in mind.  Thanks.
</I>&gt;<i>
</I>&gt;<i> On Tue, Mar 30, 2010 at 8:11 AM, Ron Hunter-Duvar 
</I>&gt;<i> &lt;<A HREF="http://www.antlr.org/mailman/listinfo/antlr-interest">ron.hunter-duvar at oracle.com</A> &lt;mailto:<A HREF="http://www.antlr.org/mailman/listinfo/antlr-interest">ron.hunter-duvar at oracle.com</A>&gt;&gt; wrote:
</I>&gt;<i>
</I>&gt;<i>     Hi Cliff,
</I>&gt;<i>
</I>&gt;<i>     I reported this same problem on February 10 on this list. It's an
</I>&gt;<i>     Antlr bug, and my emails on it had the work around (which requires
</I>&gt;<i>     you to implement a custom superclass if you haven't already). If
</I>&gt;<i>     you search the list archives you should be able to find it.
</I>&gt;<i>
</I>&gt;<i>     Ron
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>     Cliff Hudson wrote:
</I>&gt;<i>
</I>&gt;<i>         I have been trying to work through an issue with an infinite
</I>&gt;<i>         loop caused
</I>&gt;<i>         when no tokens can be matched because a predicate has failed
</I>&gt;<i>         its test.  The
</I>&gt;<i>         problem appears to be in the Lexer.NextToken() (looking at
</I>&gt;<i>         CSharp2 sources)
</I>&gt;<i>         method, which I have copied here for reference:
</I>&gt;<i>
</I>&gt;<i>                        /// &lt;summary&gt;
</I>&gt;<i>                        /// Return a token from this source; i.e.,
</I>&gt;<i>         Match a token on the char stream.
</I>&gt;<i>                        /// &lt;/summary&gt;
</I>&gt;<i>                        public virtual IToken NextToken()
</I>&gt;<i>                        {
</I>&gt;<i>                                while (true)
</I>&gt;<i>                                {
</I>&gt;<i>                                        state.token = null;
</I>&gt;<i>                                        state.channel =
</I>&gt;<i>         Token.DEFAULT_CHANNEL;
</I>&gt;<i>                                        state.tokenStartCharIndex =
</I>&gt;<i>         input.Index;
</I>&gt;<i>                                      
</I>&gt;<i>          state.tokenStartCharPositionInLine = input.CharPositionInLine;
</I>&gt;<i>                                        state.tokenStartLine = input.Line;
</I>&gt;<i>                                        state.text = null;
</I>&gt;<i>                                        if (input.LA(1) ==
</I>&gt;<i>         (int)CharStreamConstants.EOF)
</I>&gt;<i>                                        {
</I>&gt;<i>                                                return Token.EOF_TOKEN;
</I>&gt;<i>                                        }
</I>&gt;<i>                                        try
</I>&gt;<i>                                        {
</I>&gt;<i>                                                mTokens();
</I>&gt;<i>                                                if (state.token == null)
</I>&gt;<i>                                                {
</I>&gt;<i>                                                        Emit();
</I>&gt;<i>                                                }
</I>&gt;<i>                                                else if (state.token ==
</I>&gt;<i>         Token.SKIP_TOKEN)
</I>&gt;<i>                                                {
</I>&gt;<i>                                                        continue;
</I>&gt;<i>                                                }
</I>&gt;<i>                                                return state.token;
</I>&gt;<i>                                        }
</I>&gt;<i>                                        catch (NoViableAltException nva) {
</I>&gt;<i>                                                ReportError(nva);
</I>&gt;<i>                                                Recover(nva); // throw
</I>&gt;<i>         out current char and try again
</I>&gt;<i>                                        }
</I>&gt;<i>                                        catch (RecognitionException re) {
</I>&gt;<i>                                                ReportError(re);
</I>&gt;<i>                                                // Match() routine has
</I>&gt;<i>         already called Recover()
</I>&gt;<i>                                        }
</I>&gt;<i>                                }
</I>&gt;<i>                        }
</I>&gt;<i>
</I>&gt;<i>         Note the RecognitionException clause.  This is the clause
</I>&gt;<i>         which will
</I>&gt;<i>         catch the FailedPredicateException().  Unfortunately, because the
</I>&gt;<i>         FailedPredicateException gets thrown just before Match()
</I>&gt;<i>         occurs in the
</I>&gt;<i>         rule, Recover will *not* have been called by the rule or its
</I>&gt;<i>         callees,
</I>&gt;<i>         and therefore the DFA will continue to try processing the same
</I>&gt;<i>         token.
</I>&gt;<i>         It would appear that there should instead be a specific
</I>&gt;<i>         FailedPredicateException clause which does the same thing as the
</I>&gt;<i>         NoViableAltException clause.
</I>&gt;<i>
</I>&gt;<i>         I have seen two other people ask questions about this error,
</I>&gt;<i>         and in
</I>&gt;<i>         neither case was a suitable response given.  Has this bug been
</I>&gt;<i>         fixed
</I>&gt;<i>         in non-released builds?  Can someone give me an up-or-down on
</I>&gt;<i>         whether
</I>&gt;<i>         this is a correct and appropriate fix?
</I>&gt;<i>
</I>&gt;<i>         Thanks.
</I>&gt;<i>
</I>&gt;<i>         - Cliff
</I>&gt;<i>
</I>&gt;<i>         List: <A HREF="http://www.antlr.org/mailman/listinfo/antlr-interest">http://www.antlr.org/mailman/listinfo/antlr-interest</A>
</I>&gt;<i>         Unsubscribe:
</I>&gt;<i>         <A HREF="http://www.antlr.org/mailman/options/antlr-interest/your-email-address">http://www.antlr.org/mailman/options/antlr-interest/your-email-address</A>
</I>&gt;<i>
</I>&gt;<i>          
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>     -- 
</I>&gt;<i>     Ron Hunter-Duvar | Software Developer V | 403-272-6580
</I>&gt;<i>     Oracle Service Engineering
</I>&gt;<i>     Gulf Canada Square 401 - 9th Avenue S.W., Calgary, AB, Canada T2P 3C5
</I>&gt;<i>
</I>&gt;<i>     All opinions expressed here are mine, and do not necessarily represent
</I>&gt;<i>     those of my employer.
</I>&gt;<i>
</I>&gt;<i>
</I>
-- 
Ron Hunter-Duvar | Software Developer V | 403-272-6580
Oracle Service Engineering
Gulf Canada Square 401 - 9th Avenue S.W., Calgary, AB, Canada T2P 3C5

All opinions expressed here are mine, and do not necessarily represent
those of my employer.

</PRE>








<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="038092.html">[antlr-interest] FailedPredicateException leads to infinite	loop - bug in the Lexer?
</A></li>
	<LI>Next message: <A HREF="038095.html">[antlr-interest] FailedPredicateException leads to infinite	loop - bug in the Lexer?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#38093">[ date ]</a>
              <a href="thread.html#38093">[ thread ]</a>
              <a href="subject.html#38093">[ subject ]</a>
              <a href="author.html#38093">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
