<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] Parser Generation: How to catch an exception within an rule?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Parser%20Generation%3A%20How%20to%20catch%20an%20exception%0A%20within%20an%20rule%3F&In-Reply-To=%3C45F1D7DD.5050208%40gmx.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="019642.html">
   <LINK REL="Next"  HREF="019664.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] Parser Generation: How to catch an exception within an rule?</H1>
    <B>Johannes Luber</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Parser%20Generation%3A%20How%20to%20catch%20an%20exception%0A%20within%20an%20rule%3F&In-Reply-To=%3C45F1D7DD.5050208%40gmx.de%3E"
       TITLE="[antlr-interest] Parser Generation: How to catch an exception within an rule?">jaluber at gmx.de
       </A><BR>
    <I>Fri Mar  9 13:55:41 PST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="019642.html">[antlr-interest] Parser Generation: How to catch an exception	within an rule?
</A></li>
        <LI>Next message: <A HREF="019664.html">[antlr-interest] Parser Generation: How to catch an exception	within an rule?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19644">[ date ]</a>
              <a href="thread.html#19644">[ thread ]</a>
              <a href="subject.html#19644">[ subject ]</a>
              <a href="author.html#19644">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>luciano mantuaneli wrote:
&gt;<i> Greetings!
</I>&gt;<i> I have a rule called identifierStar, which throws an
</I>&gt;<i> MyOwnCheckedException exception.
</I>&gt;<i> I have another rule called importDefinition, which invokes relu x. My
</I>&gt;<i> question is how can I catch the MyOwnCheckedException exception?
</I>
Add following lines to your rule:

&gt;<i> importDefinition
</I>&gt;<i>     options {defaultErrorHandler = true;}
</I>&gt;<i>     { boolean isStatic = false; String imp = &quot;&quot;;}
</I>&gt;<i>     :    i:&quot;import&quot;^ {#i.setType(IMPORT);} ( &quot;static&quot;!
</I>&gt;<i> {#i.setType(STATIC_IMPORT);} )? imp=identifierStar SEMI!
</I>&gt;<i>     ;
</I>	exception
	catch [StarImportException e] {
		System.err.println(&quot;error&quot;);
	}
&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> identifierStar returns[String result = &quot;&quot;] throws StarImportException{
</I>&gt;<i>     StringBuilder sb = new StringBuilder(&quot;&quot;);
</I>&gt;<i> }
</I>&gt;<i>     :    i:IDENT{sb.append(i.getText());}
</I>&gt;<i>         ( DOT^ i2:IDENT {sb.append(&quot;.&quot; + i2.getText());})*
</I>&gt;<i>         ( DOT^ STAR {throw new StarImportException();})?
</I>&gt;<i>         {
</I>&gt;<i>             result = sb.toString();
</I>&gt;<i>         }
</I>&gt;<i>     ;
</I>
Best regards,
Johannes Luber

</PRE>








<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="019642.html">[antlr-interest] Parser Generation: How to catch an exception	within an rule?
</A></li>
	<LI>Next message: <A HREF="019664.html">[antlr-interest] Parser Generation: How to catch an exception	within an rule?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19644">[ date ]</a>
              <a href="thread.html#19644">[ thread ]</a>
              <a href="subject.html#19644">[ subject ]</a>
              <a href="author.html#19644">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
